 github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 gfm_quirks: paragraph_end
 baseurl: "ropenbio/"
 url: "https://mariyad.github.io/"

theme: jekyll-theme-cayman
