initial_dump_directory: /media/obkms/XML2/
turtle_directory: /media/obkms/RDF/
gazetteer:
  countries: /media/obkms/Gazetteer/country_names.csv
  cities: /media/obkms/Gazetteer/city_names.csv
  institutions: /media/obkms/Gazetteer/institution_names.csv
  institutions_no_city: /media/obkms/Gazetteer/institution_no_city.csv
bdj_endpoint: http://bdj.pensoft.net/lib/journal_archive.php?journal=bdj
zookeys_endpoint: http://zookeys.pensoft.net/lib/journal_archive.php?journal=zookeys
